"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { auth } from "@/lib/firebase/client";

type Reg = { id: string; team_name?: string; team_id: string; round_id: string; round_name?: string; series_year?: number; status: string; payment_status: string; amount: number; currency: string; paypal_order_id?: string; paypal_capture_id?: string; created_at?: string; paid_at?: string; waiting_list_position?: number; refund_status?: string; cancellation_note?: string };
type Round = { id: string; name: string; series_year?: number; event_date?: string };
export default function AdminRegistrations() {
  const [rows, setRows] = useState<Reg[]>([]); const [rounds, setRounds] = useState<Round[]>([]); const [year, setYear] = useState("all"); const [roundId, setRoundId] = useState("all"); const [status, setStatus] = useState("all"); const [message, setMessage] = useState(""); const [busy, setBusy] = useState("");
  const token = useCallback(async () => { const u = auth.currentUser; if (!u) throw new Error("Please sign in again."); return u.getIdToken(); }, []);
  const load = useCallback(async () => { const idToken = await token(); const response = await fetch("/api/registrations/admin", { headers: { Authorization: `Bearer ${idToken}` }, cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not load registrations."); setRows(data.registrations || []); setRounds(data.rounds || []); }, [token]);
  useEffect(() => { load().catch(e => setMessage(e.message)); }, [load]);
  const years = useMemo(() => Array.from(new Set([...rounds.map(r => Number(r.series_year) || (r.event_date ? new Date(`${r.event_date}T12:00:00`).getFullYear() : 0)), ...rows.map(r => Number(r.series_year) || 0)].filter(Boolean))).sort((a,b)=>b-a), [rounds, rows]);
  const visible = rows.filter(r => (year === "all" || String(r.series_year) === year) && (roundId === "all" || r.round_id === roundId) && (status === "all" || r.status === status));
  async function action(row: Reg, action: "cancel" | "record_refund") {
    const prompt = action === "cancel" ? "Optional cancellation note:" : "Confirm the refund has already been issued manually in PayPal. Enter a note/reference:";
    if (action === "cancel" && !confirm(`Cancel ${row.team_name || "this team"}'s registration? Any refund must be handled separately in PayPal.`)) return;
    const note = action === "record_refund" ? window.prompt(prompt) : window.prompt(prompt, ""); if (note === null) return;
    if (action === "record_refund" && !note.trim()) { setMessage("Enter a note or PayPal refund reference before recording the refund."); return; }
    try { setBusy(row.id); const idToken = await token(); const response = await fetch("/api/registrations/admin", { method: "PATCH", headers: { Authorization: `Bearer ${idToken}`, "Content-Type": "application/json" }, body: JSON.stringify({ registrationId: row.id, action, note }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Action failed."); setMessage(data.message || "Updated."); await load(); } catch (e: any) { setMessage(e.message); } finally { setBusy(""); }
  }
  return <div className="space"><div className="card"><h2>Manage Registrations</h2><p className="muted">Review entries and payment references. Refunds are processed manually in PayPal; recording a refund here does not issue the payment.</p><div className="grid three"><label>Series year<select className="input" value={year} onChange={e=>setYear(e.target.value)}><option value="all">All years</option>{years.map(y=><option key={y} value={String(y)}>{y}</option>)}</select></label><label>Round<select className="input" value={roundId} onChange={e=>setRoundId(e.target.value)}><option value="all">All rounds</option>{rounds.filter(r=>year==="all"||String(r.series_year || (r.event_date ? new Date(`${r.event_date}T12:00:00`).getFullYear():0))===year).map(r=><option key={r.id} value={r.id}>{r.series_year || "Year?"} — {r.name}</option>)}</select></label><label>Status<select className="input" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="registered">Registered / Paid</option><option value="payment_pending">Payment pending</option><option value="waiting_list">Waiting list</option><option value="expired">Expired</option><option value="cancelled">Cancelled</option></select></label></div>{message&&<p role="status">{message}</p>}</div>
    <div className="card"><h3>{visible.length} registration{visible.length===1?"":"s"}</h3>{!visible.length?<p className="muted">No registrations match these filters.</p>:visible.map(row=><div className="registrationAdminRow" key={row.id}><div className="registrationAdminMain"><b>{row.team_name || row.team_id}</b><div>{row.series_year} — {row.round_name || row.round_id}</div><div className="muted">Status: {row.status === "waiting_list" ? `Waiting list #${row.waiting_list_position || "—"}` : row.status.replaceAll("_", " ")} · Payment: {row.payment_status.replaceAll("_", " ")}</div><div className="muted">Amount: £{Number(row.amount || 100).toFixed(2)} {row.currency || "GBP"}{row.paid_at ? ` · Paid ${new Date(row.paid_at).toLocaleString("en-GB")}` : ""}</div>{row.paypal_order_id&&<div className="muted registrationRef">PayPal order: {row.paypal_order_id}</div>}{row.paypal_capture_id&&<div className="muted registrationRef">Capture: {row.paypal_capture_id}</div>}{row.refund_status&&<div className="muted">Refund: {row.refund_status}</div>}</div><div className="registrationAdminActions">{row.status!=="cancelled"&&<button className="btn danger small" disabled={!!busy} onClick={()=>action(row,"cancel")}>Cancel</button>}{row.payment_status==="paid"&&row.status==="cancelled"&&row.refund_status!=="refunded_manually"&&<button className="btn secondary small" disabled={!!busy} onClick={()=>action(row,"record_refund")}>Record manual refund</button>}</div></div>)}</div>
  </div>;
}
